blueprint:
  name: HVAC Calibrator
  description: Calibrate your HVAC using an external sensor and a numeric input entity to store 2 offsets (for heating/cooling). Offset values are rounded to 0.5 degrees.
  domain: automation
  input:
    hvac:
      name: HVAC Climate Entity
      selector:
        entity:
          domain: climate
    temperature_sensor:
      name: Temperature Sensor
      description: Sensor used to calibrate your HVAC
      selector:
        entity:
          domain: sensor
          device_class: temperature
    hvac_offset_heat:
      name: TRV Offset Entity Heat Mode
      description: Offset entity for heating mode (i.e. HVAC setpoint - target room temperature)
      selector:
        entity:
          domain: input_number
    hvac_offset_cool:
      name: TRV Offset Entity Cooling Mode
      description: Offset entity for cooling mode (i.e. HVAC setpoint - target room temperature)
      selector:
        entity:
          domain: input_number
    interval_in_minutes:
      name: Interval to periodically update offsets
      description: Periodically check the offset between setpoint and external sensor every few minutes
      default: 20
      selector:
        number:
          min: 1
          max: 60
          step: 1
    delay_in_minutes:
      name: Delay in minutes
      description: Initial delay to update offsets after changing the HVAC mode.
      default: 5
      selector:
        number:
          min: 1
          max: 60
          step: 1

mode: restart

variables:
  hvac: !input hvac
  hvac_offset_heat: !input hvac_offset_heat
  hvac_offset_cool: !input hvac_offset_cool
  temperature_sensor: !input temperature_sensor                                

trigger:
  - platform: state
    entity_id: !input hvac
    id: hvac_state
    from: "off"
    to:
      - "heat"
      - "cool"
    for:
      hours: 0
      minutes: !input delay_in_minutes
      seconds: 0
  - platform: state
    entity_id: !input hvac_offset_heat
    id: hvac_heat_offset
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: state
    entity_id: !input hvac_offset_cool
    id: hvac_cool_offset
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: time_pattern
    id: hvac_timer
    minutes: !input interval_in_minutes

condition:
  - condition: template
    value_template: '{{ state_attr(hvac, "temperature") != None }}'
  - condition: template
    value_template: '{{ states(hvac_offset_heat) != "unavailable" and states(hvac_offset_heat) != "unknown" }}'
  - condition: template
    value_template: '{{ states(hvac_offset_cool) != "unavailable" and states(hvac_offset_cool) != "unknown" }}'
  - condition: template
    value_template: '{{ states(temperature_sensor) != "unavailable" and states(temperature_sensor) != "unknown" }}'

action:
  - choose:
      - alias: 'HVAC turned on to heat/cool'
        conditions:
          - condition: trigger
            id:
              - hvac_state
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input hvac
            data:
              temperature: >
                {% set old_state = trigger.from_state.state %}
                {% set current_set_temp = state_attr(hvac, "temperature") | float %}
                {% set current_offset_heat = states(hvac_offset_heat) | float %}
                {% set current_offset_cool = states(hvac_offset_cool) | float %}
                {% set current_mode = states(hvac) %}
                {% if current_mode == 'heat' -%}
                  {{ current_set_temp + current_offset_heat }}
                {%- elif current_mode == 'cool' %} 
                  {{ current_set_temp + current_offset_cool }}
                {%- else -%}
                  {{ current_set_temp }}
                {%- endif %}

      - alias: 'HVAC cooling offset update timer'
        conditions:
          - condition: trigger
            id:
              - hvac_timer
          - condition: state
            entity_id: !input hvac
            state: 'cool'
        sequence:
          - service: input_number.set_value
            target:
              entity_id: !input hvac_offset_cool
            data:
              value: >- 
                {% set room_temperature = states(temperature_sensor) | float %}
                {% set hvac_temperature = state_attr(hvac, "temperature") | float %}              
                {{ (hvac_temperature - room_temperature) | round(1, 'half', 0) }}

      - alias: 'HVAC heating offset update timer'
        conditions:
          - condition: trigger
            id:
              - hvac_timer
          - condition: state
            entity_id: !input hvac
            state: 'heat'
        sequence:
          - service: input_number.set_value
            target:
              entity_id: !input hvac_offset_heat
            data:
              value: >- 
                {% set room_temperature = states(temperature_sensor) | float %}
                {% set hvac_temperature = state_attr(hvac, "temperature") | float %}              
                {{ (hvac_temperature - room_temperature) | round(1, 'half', 0) }}
      
      - alias: 'HVAC heating offset changed'
        conditions:
          - condition: trigger
            id:
              - hvac_heat_offset
        sequence:
          - service: system_log.write
            data:
              message: 'HVAC heating offset changed: {{trigger.from_state.state}} -> {{trigger.to_state.state}}'
              level: info

      - alias: 'HVAC cooling offset changed'
        conditions:
        - condition: trigger
          id:
            - hvac_cool_offset
        sequence:
          - service: system_log.write
            data:
              message: 'HVAC cooling offset changed: {{trigger.from_state.state}} -> {{trigger.to_state.state}}'
              level: info
 